return {
    { 'altercation/vim-colors-solarized' },
    { 'euclidianAce/BetterLua.vim' },
    { 'gpanders/vim-medieval' },
    { 'mhinz/vim-grepper' },
    { 'mhinz/vim-signify' },
    { 'nvim-lua/plenary.nvim' },
    { 'pedrohdz/vim-yaml-folds' },
    { 'rhysd/vim-grammarous' },
    { 'sukima/xmledit' },
    { 'vim-pandoc/vim-pandoc-syntax' },
    { 'vim-scripts/DoxygenToolkit.vim' },
    { 'kyazdani42/nvim-web-devicons' },
    { 'dccsillag/magma-nvim', build = ':UpdateRemotePlugins' },
    { 'euclio/vim-markdown-composer', build = { 'cargo build --release', ':UpdateRemotePlugins' } },
    { 'petertriho/cmp-git', dependencies = { 'nvim-lua/plenary.nvim' } },
    { "folke/todo-comments.nvim", dependencies = { "nvim-lua/plenary.nvim" } },
}
